import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Generated by scripts/generate-agent-ui.ts in the mnemex repo.
//
// AgentCanvas ships this file wired to its bundled Pi agent runtime, which mounts itself
// into the dev server as a Vite plugin. mnemex replaces that runtime wholesale: the agent
// loop lives in ../agent-ui/server and needs the mnemex node_modules to reach Neo4j, so it
// runs as its own process and the dev server proxies to it.
export default defineConfig({
  base: "./",
  plugins: [react()],
  server: {
    proxy: {
      "/__agentcanvas/pi": {
        target: "http://127.0.0.1:8787",
        changeOrigin: false,
        // Tool loops outlive the default proxy timeout, and buffering would defeat the
        // point of streaming the tokens in the first place.
        timeout: 0,
        proxyTimeout: 0,
      },
    },
  },
  resolve: {
    // The vendored @agent-ux/* packages are linked via `file:./vendor/...` and import bare
    // "react"/"react-dom". Without dedupe the bundler may resolve those from the vendor
    // folder, which has no node_modules of its own, and the app dies with
    // `Cannot read properties of null (reading 'useMemo')`.
    dedupe: ["react", "react-dom"],
  },
});
